Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def f(x):
    return x**2

x_list = list(range(1, 21))
x_array = np.arange(1, 21)
f(x_list)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[8], line 6[0m
[1;32m      4[0m x_list [38;5;241m=[39m [38;5;28mlist[39m([38;5;28mrange[39m([38;5;241m1[39m, [38;5;241m21[39m))
[1;32m      5[0m x_array [38;5;241m=[39m np[38;5;241m.[39marange([38;5;241m1[39m, [38;5;241m21[39m)
[0;32m----> 6[0m [43mf[49m[43m([49m[43mx_list[49m[43m)[49m

Cell [0;32mIn[8], line 2[0m, in [0;36mf[0;34m(x)[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mf[39m(x):
[0;32m----> 2[0m     [38;5;28;01mreturn[39;00m [43mx[49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[38;5;241;43m2[39;49m

[0;31mTypeError[0m: unsupported operand type(s) for ** or pow(): 'list' and 'int'

